name: SST workflow
on:
  push:
    branches:
    - main
    tags-ignore:
      - '**'
  pull_request:
    types:
      - opened

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ vars.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1
      - name: Deploy app
        run: |
          bun install && bun sst deploy --stage prod
