name: Deployment (Staging)

on:
  push:
    branches:
      - 'main'
      - 'release/**'
    tags-ignore:
      - '*'

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write
  actions: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: Staging
    secrets: inherit


  deploy:
    needs: [test, build]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Staging
      stage: staging
    secrets: inherit